basePath: /api
definitions:
  common.JSONResponse:
    properties:
      isSuccess:
        type: boolean
      items: {}
      message:
        type: string
    type: object
  entities.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        type: string
      id:
        type: integer
      updatedAt:
        type: string
      username:
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  paginate.Page:
    properties:
      error:
        type: boolean
      error_message:
        type: string
      first:
        type: boolean
      items: {}
      last:
        type: boolean
      max_page:
        type: integer
      page:
        type: integer
      size:
        type: integer
      total:
        type: integer
      total_pages:
        type: integer
      visible:
        type: integer
    type: object
  users.UserInput:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  users.UserPage:
    properties:
      ID:
        type: integer
      email:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Example API
  version: "1.0"
paths:
  /v1/users:
    get:
      consumes:
      - application/json
      description: Get a paginated list of users
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Size
        in: query
        name: size
        type: integer
      - description: Sort
        in: query
        name: sort
        type: string
      - description: Filter
        in: query
        name: filters
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/paginate.Page'
            - properties:
                items:
                  items:
                    $ref: '#/definitions/users.UserPage'
                  type: array
              type: object
      summary: List users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create a new user with the provided details
      parameters:
      - description: User details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/users.UserInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/common.JSONResponse'
            - properties:
                items:
                  type: integer
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.JSONResponse'
      summary: Create a new user
      tags:
      - users
  /v1/users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.JSONResponse'
      summary: Delete user
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Get detailed information about a user by their ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.JSONResponse'
            - properties:
                items:
                  $ref: '#/definitions/entities.User'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.JSONResponse'
      summary: Get user by ID
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update an existing user's details
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated user details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/users.UserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.JSONResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.JSONResponse'
      summary: Update user
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
